# Generated by Django 3.1.2 on 2021-11-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a post status', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a post type', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=200)),
                ('content', models.TextField(help_text='Enter content', max_length=500)),
                ('staff', models.CharField(help_text='Enter staff', max_length=50)),
                ('date', models.DateField(auto_now_add=True, help_text='Enter date')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.type')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
