# Generated by Django 3.1.2 on 2022-01-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220112_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.file'),
        ),
    ]
