# Generated by Django 3.1.2 on 2022-01-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20220112_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
    ]
