# Generated by Django 3.1.2 on 2022-01-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20220112_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', help_text='Enter filename', max_length=20),
        ),
    ]
