# Generated by Django 3.1.2 on 2022-01-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_file_filename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Files',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(blank=True, to='news.Files'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter content', max_length=1500),
        ),
    ]
