# Generated by Django 3.1.2 on 2022-01-25 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20220125_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': '公告狀態'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name_plural': '公告類型'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='輸入內容', max_length=1500, verbose_name='公告內容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='公告日期'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='附加檔案一'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='附加檔案二'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='附加檔案三'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='附加檔案四'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片一'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片二'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片三'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片四'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, help_text='輸入連結網址', null=True, verbose_name='相關連結'),
        ),
        migrations.AlterField(
            model_name='post',
            name='staff',
            field=models.CharField(help_text='輸入人員', max_length=50, verbose_name='公告人員'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.status', verbose_name='公告狀態'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='輸入標題', max_length=200, verbose_name='公告標題'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.type', verbose_name='公告類型'),
        ),
    ]
