# Generated by Django 3.1.2 on 2022-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20220125_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('一般', '一般'), ('重要', '重要'), ('大學部', '大學部'), ('碩士', '碩士'), ('博士', '博士')], default='一般', max_length=10),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('一般資訊', '一般資訊'), ('徵人資訊', '徵人資訊'), ('招生資訊', '招生資訊'), ('獲獎資訊', '獲獎資訊'), ('演講資訊', '演講資訊'), ('獎助學金', '獎助學金')], default='一般資訊', max_length=10),
        ),
    ]
