# Generated by Django 3.1.2 on 2022-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20220216_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ontop',
            field=models.BooleanField(default=False, verbose_name='置頂'),
        ),
    ]
