# Generated by Django 3.1.2 on 2022-02-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_post_ontop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['is_pin', '-date'], 'verbose_name_plural': '公告'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ontop',
            new_name='is_pin',
        ),
    ]
