# Generated by Django 3.1.2 on 2022-02-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20220216_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pin', '-date'], 'verbose_name_plural': '公告'},
        ),
    ]
