# Generated by Django 3.1.2 on 2022-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_auto_20220216_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ManyToManyField(to='news.Type', verbose_name='公告類型'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Enter a post type', max_length=10),
        ),
    ]
