# Generated by Django 3.1.2 on 2022-04-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_auto_20220329_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('一般', '一般'), ('重要', '重要'), ('大學部', '大學部'), ('畢業生', '碩士'), ('博士', '博士'), ('畢業生', '畢業生')], default='一般', max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Enter a post type', max_length=20),
        ),
    ]
