# Generated by Django 3.1.2 on 2022-04-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_auto_20220421_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('一般', '一般'), ('重要', '重要'), ('大學部', '大學部'), ('碩士', '碩士'), ('博士', '博士'), ('畢業生', '畢業生')], default='一般', max_length=20),
        ),
    ]
