# Generated by Django 3.1.2 on 2022-05-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_auto_20220518_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfile',
            options={'verbose_name_plural': '附加檔案'},
        ),
        migrations.AlterField(
            model_name='postfile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='news.post'),
        ),
    ]
