# Generated by Django 3.1.2 on 2022-08-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_post_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pin', '-updated_at', '-date'], 'verbose_name_plural': '公告'},
        ),
    ]
