# Generated by Django 3.1.2 on 2022-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_auto_20220804_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pin', '-update_date', '-date'], 'verbose_name_plural': '公告'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
