# Generated by Django 3.1.2 on 2022-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_auto_20220805_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日期'),
        ),
    ]
