# Generated by Django 3.1.2 on 2022-08-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_auto_20220805_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, help_text='輸入標題', max_length=200, null=True, verbose_name='英文公告標題'),
        ),
    ]
