# Generated by Django 3.1.2 on 2022-08-16 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0048_post_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='更新日期'),
        ),
    ]
