# Generated by Django 3.1.2 on 2022-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0049_auto_20220816_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, help_text='輸入英文內容(非必填)', null=True, verbose_name='英文公告內容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, help_text='輸入英文標題(非必填)', max_length=200, null=True, verbose_name='英文公告標題'),
        ),
    ]
