# Generated by Django 3.1.2 on 2022-03-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='輸入標題', max_length=200, verbose_name='大標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='內容')),
                ('subtitle1', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題一')),
                ('subcontent1', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題一內容')),
                ('subtitle2', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題二')),
                ('subcontent2', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題二內容')),
                ('subtitle3', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題三')),
                ('subcontent3', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題三內容')),
            ],
            options={
                'verbose_name_plural': '課程介紹',
                'ordering': ['-title'],
            },
        ),
    ]
