# Generated by Django 3.1.2 on 2022-08-09 09:27

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_bachelor_bachelortranslation_documents_documentstranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '文件下載',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TextInfoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='輸入標題', max_length=200, verbose_name='標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', verbose_name='內容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='圖片')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='education.textinfo')),
            ],
            options={
                'verbose_name': 'text info Translation',
                'db_table': 'education_textinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a post type', max_length=20)),
            ],
            options={
                'verbose_name_plural': '資訊類型',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bachelortranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bachelortranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='documentstranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentstranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Bachelor',
        ),
        migrations.DeleteModel(
            name='BachelorTranslation',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='DocumentsTranslation',
        ),
        migrations.AddField(
            model_name='textinfotranslation',
            name='type',
            field=models.ManyToManyField(to='education.Type', verbose_name='類型'),
        ),
        migrations.AlterUniqueTogether(
            name='textinfotranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
