# Generated by Django 3.1.2 on 2022-08-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20220809_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textinfo',
            options={'verbose_name_plural': '文字資訊'},
        ),
        migrations.RemoveField(
            model_name='textinfotranslation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='textinfotranslation',
            name='type',
        ),
        migrations.AddField(
            model_name='textinfo',
            name='type',
            field=models.ManyToManyField(to='education.Type', verbose_name='類型'),
        ),
    ]
