# Generated by Django 3.1.2 on 2022-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsiePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name_plural': '系上形象圖片',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='carousel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
    ]
