# Generated by Django 3.1.2 on 2022-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220211_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='csiepicture',
            name='content',
            field=models.TextField(blank=True, help_text='輸入內容', max_length=100, null=True, verbose_name='圖片內容'),
        ),
    ]
