# Generated by Django 3.1.2 on 2022-02-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_link_navbar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date'], 'verbose_name_plural': '圖片'},
        ),
    ]
