# Generated by Django 3.1.2 on 2022-02-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_navbar_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(choices=[('info', '本系簡介'), ('members', '師資陣容'), ('news', '系所公告'), ('admission', '招生資訊')], default='news', max_length=20),
        ),
    ]
