# Generated by Django 3.1.2 on 2022-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_itnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='externalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='輸入名稱', max_length=100, verbose_name='名稱')),
                ('icon', models.ImageField(upload_to='images/icon', verbose_name='圖片')),
                ('description', models.TextField(blank=True, help_text='輸入內容', max_length=100, null=True, verbose_name='圖片描述')),
                ('link', models.URLField(help_text='輸入連結網址', max_length=500, verbose_name='相關連結')),
            ],
            options={
                'verbose_name_plural': '相關連結',
            },
        ),
        migrations.CreateModel(
            name='homeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='圖片')),
            ],
            options={
                'verbose_name_plural': '首頁圖片',
            },
        ),
        migrations.CreateModel(
            name='homeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='輸入標題', max_length=200, verbose_name='標題')),
                ('content', models.TextField(help_text='輸入內容', max_length=200, verbose_name='內容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片')),
                ('link', models.URLField(blank=True, help_text='輸入連結網址', null=True, verbose_name='相關連結')),
            ],
            options={
                'verbose_name_plural': '首頁文字',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date'], 'verbose_name_plural': '輪播圖片'},
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(choices=[('本系簡介', '本系簡介'), ('師資陣容', '師資陣容'), ('系所公告', '系所公告'), ('招生資訊', '招生資訊')], default='系所公告', max_length=20, verbose_name='連結'),
        ),
    ]
