# Generated by Django 3.1.2 on 2022-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220305_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='輸入標題', max_length=200, verbose_name='標題')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片')),
            ],
            options={
                'verbose_name_plural': '首頁圖片',
            },
        ),
        migrations.AlterModelOptions(
            name='homeinfo',
            options={'verbose_name_plural': '首頁文字'},
        ),
    ]
