# Generated by Django 3.1.2 on 2022-03-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220305_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='image',
            field=models.ImageField(default=3, upload_to='images/', verbose_name='圖片'),
            preserve_default=False,
        ),
    ]
