# Generated by Django 3.1.2 on 2022-03-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220305_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date'], 'verbose_name_plural': '輪播圖片'},
        ),
    ]
