# Generated by Django 3.1.2 on 2022-03-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220307_1326'),
        ('home', '0017_auto_20220305_1739'),
    ]

    operations = [
    ]
