# Generated by Django 3.1.2 on 2022-04-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_merge_20220319_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(choices=[('info', '本系簡介'), ('師資陣容', '師資陣容'), ('系所公告', '系所公告'), ('招生資訊', '招生資訊')], default='系所公告', max_length=20, verbose_name='連結'),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='輸入分頁名稱', max_length=20)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.link', verbose_name='分頁連結')),
            ],
            options={
                'verbose_name_plural': '連結',
                'ordering': ['name'],
            },
        ),
    ]
