# Generated by Django 3.1.2 on 2022-04-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220423_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='links',
        ),
        migrations.AddField(
            model_name='navbar',
            name='links',
            field=models.CharField(choices=[('info', '本系簡介'), ('1', 'JANUARY'), ('2', 'FEBRUARY'), ('3', 'MAR')], default='info', max_length=20),
        ),
    ]
