# Generated by Django 3.1.2 on 2022-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20220423_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='links',
        ),
        migrations.AddField(
            model_name='navbar',
            name='links',
            field=models.ManyToManyField(to='home.Link', verbose_name='首頁連結'),
        ),
    ]
