# Generated by Django 3.1.2 on 2022-07-19 09:17

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220518_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinfo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='title',
        ),
        migrations.CreateModel(
            name='homeInfoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='輸入標題', max_length=200, verbose_name='標題')),
                ('content', models.TextField(help_text='輸入內容', max_length=200, verbose_name='內容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片')),
                ('link', models.URLField(blank=True, help_text='輸入連結網址', null=True, verbose_name='相關連結')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homeinfo')),
            ],
            options={
                'verbose_name': 'home info Translation',
                'db_table': 'home_homeinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
    ]
