# Generated by Django 3.1.2 on 2022-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20220821_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(default='', max_length=50, verbose_name='顯示文字'),
        ),
    ]
