# Generated by Django 3.1.2 on 2022-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20220826_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimagetranslation',
            name='image',
            field=models.ImageField(upload_to='images/homeImage', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='homeinfotranslation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/homeInfo', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='itnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ITnews', verbose_name='圖片'),
        ),
    ]
