# Generated by Django 4.1 on 2022-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0043_auto_20220828_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carousel",
            name="csie",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/home/carousel",
                verbose_name="系上形象圖片",
            ),
        ),
        migrations.AlterField(
            model_name="externallink",
            name="icon",
            field=models.ImageField(upload_to="images/home/icon", verbose_name="圖片"),
        ),
        migrations.AlterField(
            model_name="homeimagetranslation",
            name="image",
            field=models.ImageField(
                upload_to="images/home/homeImage", verbose_name="圖片"
            ),
        ),
        migrations.AlterField(
            model_name="homeinfotranslation",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/home/homeInfo",
                verbose_name="圖片",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/home/carousel",
                verbose_name="圖片",
            ),
        ),
        migrations.AlterField(
            model_name="itnews",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/home/ITnews", verbose_name="圖片"
            ),
        ),
    ]
