# Generated by Django 4.1 on 2022-09-04 07:02

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0044_alter_carousel_csie_alter_externallink_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externallink",
            name="description",
        ),
        migrations.RemoveField(
            model_name="externallink",
            name="name",
        ),
        migrations.CreateModel(
            name="externalLinkTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="輸入名稱", max_length=100, verbose_name="名稱"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="輸入內容", null=True, verbose_name="圖片描述"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="home.externallink",
                    ),
                ),
            ],
            options={
                "verbose_name": "external link Translation",
                "db_table": "home_externallink_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
