# Generated by Django 4.1.1 on 2022-09-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0045_remove_externallink_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externallink", options={"verbose_name_plural": "外部相關連結"},
        ),
        migrations.AlterModelOptions(
            name="homeimage", options={"verbose_name_plural": "地圖"},
        ),
        migrations.AlterModelOptions(
            name="homeinfo", options={"verbose_name_plural": "文字訊息"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-date"], "verbose_name_plural": "圖片上傳"},
        ),
        migrations.AlterModelOptions(
            name="link", options={"verbose_name_plural": "快速連結"},
        ),
    ]
