# Generated by Django 4.1 on 2022-09-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0047_alter_image_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times", models.IntegerField()),
            ],
        ),
    ]
