# Generated by Django 3.1.2 on 2022-07-20 08:25

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_centers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name_plural': '研究群'},
        ),
        migrations.AlterModelOptions(
            name='centers',
            options={'verbose_name_plural': '研究中心'},
        ),
        migrations.RemoveField(
            model_name='areas',
            name='content',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='date',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='image',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='title',
        ),
        migrations.RemoveField(
            model_name='centers',
            name='content',
        ),
        migrations.RemoveField(
            model_name='centers',
            name='date',
        ),
        migrations.RemoveField(
            model_name='centers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='centers',
            name='link',
        ),
        migrations.RemoveField(
            model_name='centers',
            name='title',
        ),
        migrations.CreateModel(
            name='CentersTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='輸入標題', max_length=200, verbose_name='標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', verbose_name='內容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='圖片')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True, help_text='輸入連結網址', null=True, verbose_name='相關連結')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='research.centers')),
            ],
            options={
                'verbose_name': 'centers Translation',
                'db_table': 'research_centers_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='AreasTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='輸入標題', max_length=200, verbose_name='標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', verbose_name='內容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='圖片')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='research.areas')),
            ],
            options={
                'verbose_name': 'areas Translation',
                'db_table': 'research_areas_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
    ]
