# Generated by Django 3.1.2 on 2022-08-05 13:33

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20220720_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '國際合作交流',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InternationalTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='輸入標題', max_length=200, verbose_name='標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', verbose_name='內容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='圖片')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True, help_text='輸入連結網址', null=True, verbose_name='相關連結')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='research.international')),
            ],
            options={
                'verbose_name': 'international Translation',
                'db_table': 'research_international_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
