# Generated by Django 3.1.2 on 2022-08-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_international_internationaltranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areastranslation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='areastranslation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='centerstranslation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='centerstranslation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='centerstranslation',
            name='link',
        ),
        migrations.RemoveField(
            model_name='internationaltranslation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='internationaltranslation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='internationaltranslation',
            name='link',
        ),
    ]
