# Generated by Django 3.1.2 on 2022-08-05 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20220805_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='areastranslation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centerstranslation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internationaltranslation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
