# Generated by Django 3.1.2 on 2022-08-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20220805_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerstranslation',
            name='link',
            field=models.URLField(blank=True, help_text='輸入連結網址', null=True, verbose_name='相關連結'),
        ),
    ]
