# Generated by Django 3.1.2 on 2022-01-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=200)),
                ('content', models.TextField(help_text='Enter content', max_length=1000)),
                ('subtitle', models.TextField(help_text='Enter subtitle', max_length=200)),
                ('subcontent', models.TextField(help_text='Enter content', max_length=1000)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
