# Generated by Django 3.1.2 on 2022-01-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='subcontent',
        ),
        migrations.RemoveField(
            model_name='info',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='info',
            name='subcontent1',
            field=models.TextField(blank=True, help_text='Enter content', max_length=1000),
        ),
        migrations.AddField(
            model_name='info',
            name='subcontent2',
            field=models.TextField(blank=True, help_text='Enter content', max_length=1000),
        ),
        migrations.AddField(
            model_name='info',
            name='subcontent3',
            field=models.TextField(blank=True, help_text='Enter content', max_length=1000),
        ),
        migrations.AddField(
            model_name='info',
            name='subtitle1',
            field=models.TextField(blank=True, help_text='Enter subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='info',
            name='subtitle2',
            field=models.TextField(blank=True, help_text='Enter subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='info',
            name='subtitle3',
            field=models.TextField(blank=True, help_text='Enter subtitle', max_length=200),
        ),
    ]
