# Generated by Django 3.1.2 on 2022-01-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20220110_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.TextField(help_text='Enter title', max_length=200),
        ),
    ]
