# Generated by Django 3.1.2 on 2022-01-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20220110_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(help_text='Enter title', max_length=200),
        ),
    ]
