# Generated by Django 3.1.2 on 2022-01-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20220110_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(blank=True, help_text='Enter content', max_length=1000),
        ),
    ]
