# Generated by Django 3.1.2 on 2022-01-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20220110_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-title'], 'verbose_name_plural': '系所介紹'},
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(blank=True, help_text='Enter content', max_length=1000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subcontent1',
            field=models.TextField(blank=True, help_text='Enter content', max_length=1000, verbose_name='小標題一內容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subcontent2',
            field=models.TextField(blank=True, help_text='Enter content', max_length=1000, verbose_name='小標題二內容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subcontent3',
            field=models.TextField(blank=True, help_text='Enter content', max_length=1000, verbose_name='小標題三內容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subtitle1',
            field=models.TextField(blank=True, help_text='Enter subtitle', max_length=200, verbose_name='小標題一'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subtitle2',
            field=models.TextField(blank=True, help_text='Enter subtitle', max_length=200, verbose_name='小標題二'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subtitle3',
            field=models.TextField(blank=True, help_text='Enter subtitle', max_length=200, verbose_name='小標題三'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(help_text='Enter title', max_length=200, verbose_name='大標題'),
        ),
    ]
