# Generated by Django 3.1.2 on 2022-01-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20220125_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subcontent1',
            field=models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題一內容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subcontent2',
            field=models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題二內容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subcontent3',
            field=models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題三內容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subtitle1',
            field=models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題一'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subtitle2',
            field=models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題二'),
        ),
        migrations.AlterField(
            model_name='info',
            name='subtitle3',
            field=models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題三'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(help_text='輸入標題', max_length=200, verbose_name='大標題'),
        ),
    ]
