# Generated by Django 3.1.2 on 2022-04-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20220125_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='輸入標題', max_length=200, verbose_name='大標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='內容')),
                ('subtitle1', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題一')),
                ('subcontent1', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題一內容')),
                ('subtitle2', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題二')),
                ('subcontent2', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題二內容')),
                ('subtitle3', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題三')),
                ('subcontent3', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='小標題三內容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': '交通資訊',
                'ordering': ['-title'],
            },
        ),
    ]
