# Generated by Django 3.1.2 on 2022-04-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_visiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='輸入標題', max_length=200, verbose_name='大標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', max_length=1000, verbose_name='內容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': '場地租借',
                'ordering': ['-title'],
            },
        ),
    ]
