# Generated by Django 3.1.2 on 2022-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20220408_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(blank=True, help_text='輸入標題', max_length=200, verbose_name='標題'),
        ),
    ]
