# Generated by Django 3.1.2 on 2022-04-08 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20220408_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiting',
            options={'ordering': ['date'], 'verbose_name_plural': '交通資訊'},
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='subcontent1',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='subcontent2',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='subcontent3',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='subtitle1',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='subtitle2',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='subtitle3',
        ),
        migrations.AddField(
            model_name='visiting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visiting',
            name='title',
            field=models.CharField(blank=True, help_text='輸入標題', max_length=200, verbose_name='標題'),
        ),
    ]
