# Generated by Django 3.1.2 on 2022-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20220408_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='圖片'),
        ),
    ]
