# Generated by Django 3.1.2 on 2022-04-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['date'], 'verbose_name_plural': '設備介紹'},
        ),
    ]
