# Generated by Django 3.1.2 on 2022-07-20 07:26

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_delete_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': '系所介紹'},
        ),
        migrations.RemoveField(
            model_name='info',
            name='content',
        ),
        migrations.RemoveField(
            model_name='info',
            name='subcontent1',
        ),
        migrations.RemoveField(
            model_name='info',
            name='subcontent2',
        ),
        migrations.RemoveField(
            model_name='info',
            name='subcontent3',
        ),
        migrations.RemoveField(
            model_name='info',
            name='subtitle1',
        ),
        migrations.RemoveField(
            model_name='info',
            name='subtitle2',
        ),
        migrations.RemoveField(
            model_name='info',
            name='subtitle3',
        ),
        migrations.RemoveField(
            model_name='info',
            name='title',
        ),
        migrations.CreateModel(
            name='InfoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='輸入標題', max_length=200, verbose_name='大標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', verbose_name='內容')),
                ('subtitle1', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題一')),
                ('subcontent1', models.TextField(blank=True, help_text='輸入內容', verbose_name='小標題一內容')),
                ('subtitle2', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題二')),
                ('subcontent2', models.TextField(blank=True, help_text='輸入內容', verbose_name='小標題二內容')),
                ('subtitle3', models.TextField(blank=True, help_text='輸入小標題', max_length=200, verbose_name='小標題三')),
                ('subcontent3', models.TextField(blank=True, help_text='輸入內容', verbose_name='小標題三內容')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='info.info')),
            ],
            options={
                'verbose_name': 'info Translation',
                'db_table': 'info_info_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
    ]
