# Generated by Django 3.1.2 on 2022-07-20 07:48

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20220720_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiting',
            options={'verbose_name_plural': '交通資訊'},
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='content',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='title',
        ),
        migrations.CreateModel(
            name='VisitingTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='輸入標題', max_length=200, verbose_name='標題')),
                ('content', models.TextField(blank=True, help_text='輸入內容', verbose_name='內容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='圖片')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='info.visiting')),
            ],
            options={
                'verbose_name': 'visiting Translation',
                'db_table': 'info_visiting_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
    ]
