# Generated by Django 3.1.2 on 2022-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_textinfo_textinfotranslation_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.AlterField(
            model_name='visitingtranslation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/visiting'),
        ),
    ]
