# Generated by Django 4.1 on 2022-08-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0021_auto_20220828_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitingtranslation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/info/visiting"
            ),
        ),
    ]
