# Generated by Django 3.1.2 on 2022-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_textinfo_textinfotranslation_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eecstranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eecstranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='nckutranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nckutranslation',
            name='master',
        ),
        migrations.AlterField(
            model_name='othertranslation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/other'),
        ),
        migrations.DeleteModel(
            name='EECS',
        ),
        migrations.DeleteModel(
            name='EECSTranslation',
        ),
        migrations.DeleteModel(
            name='NCKU',
        ),
        migrations.DeleteModel(
            name='NCKUTranslation',
        ),
    ]
