# Generated by Django 3.1.2 on 2021-12-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Department Name', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('office', models.CharField(default='資訊系館', max_length=100)),
                ('Email1', models.EmailField(default='', max_length=254)),
                ('Email2', models.EmailField(blank=True, default='', max_length=254)),
                ('Email3', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('lab', models.CharField(default='', max_length=20)),
                ('Expertise', models.TextField(default='')),
                ('graduate', models.TextField(default='')),
                ('experience', models.TextField(blank=True, default='')),
                ('awarded', models.TextField(blank=True, default='')),
                ('edit_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name', max_length=10)),
                ('position', models.CharField(default='行政組員', max_length=100)),
                ('Resbonsibility', models.CharField(default='負責業務：', max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('edit_time', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_master', models.TextField(default='', help_text="Enter all the master students' name", max_length=200)),
                ('name_doctor', models.TextField(default='', help_text="Enter all the doctor students' name", max_length=200)),
                ('honor', models.TextField(default='')),
                ('conference', models.TextField(default='')),
                ('professor_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('type', models.CharField(choices=[('b', 'book'), ('a', 'accepted papers to be published'), ('r', 'refereed paper'), ('d', 'domestic conference paper'), ('f', 'foreign conference paper')], default='a', max_length=1)),
                ('professor_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('start_time', models.DateField(auto_now_add=True)),
                ('subsidy', models.CharField(default='國科會', help_text='請輸入補助單位', max_length=100)),
                ('type', models.CharField(choices=[('m', '科技部計畫'), ('g', '一般建教案')], default='m', max_length=1)),
                ('professor_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('application_number', models.CharField(default='', help_text='請輸入申請號', max_length=20)),
                ('publication_number', models.CharField(default='', help_text='請輸入公開號', max_length=20)),
                ('patent_number', models.CharField(default='', help_text='請輸入證書號', max_length=20)),
                ('IPC', models.CharField(default='', help_text='請輸入IPC', max_length=100)),
                ('country', models.CharField(default='', max_length=20)),
                ('patentee', models.CharField(default='', help_text='請輸入當前專利權人', max_length=100)),
                ('inventor', models.CharField(default='', help_text='請輸入發明人', max_length=100)),
                ('professor_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
    ]
