# Generated by Django 3.1.2 on 2021-12-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_time',
        ),
    ]
