# Generated by Django 3.1.2 on 2021-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_project_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.DateField(default='2111-02-05'),
        ),
    ]
