# Generated by Django 3.1.2 on 2021-12-10 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20211210_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finish_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
