# Generated by Django 3.1.2 on 2021-12-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20211210_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('name', models.CharField(default='', max_length=500)),
                ('professor_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('name', models.CharField(default='', max_length=500)),
                ('professor_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('grade', models.CharField(choices=[('1', 'master'), ('2', 'PhD')], max_length=1)),
                ('professor_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
