# Generated by Django 3.1.2 on 2021-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20211210_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.CharField(default='https://', max_length=100),
        ),
    ]
