# Generated by Django 3.1.2 on 2021-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='published',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student_conference',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student_honor',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student_name',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, default='https://', max_length=100),
        ),
    ]
