# Generated by Django 3.1.2 on 2021-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20211210_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Expertise',
            new_name='expertise',
        ),
        migrations.AddField(
            model_name='member',
            name='lab_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
