# Generated by Django 3.1.2 on 2021-12-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
