# Generated by Django 3.1.2 on 2021-12-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20211211_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/'),
        ),
    ]
