# Generated by Django 3.1.2 on 2021-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20211212_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/%Y/%m/%d/'),
        ),
    ]
