# Generated by Django 3.1.2 on 2022-01-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20220110_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='經歷',
            new_name='experience',
        ),
    ]
