# Generated by Django 3.1.2 on 2022-01-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20220110_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='experience',
        ),
    ]
