# Generated by Django 3.1.2 on 2022-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_honor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='inventor',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='patentee',
        ),
        migrations.AlterField(
            model_name='patent',
            name='IPC',
            field=models.CharField(default='', help_text='請輸入IPC（國際專利分類）', max_length=100),
        ),
    ]
