# Generated by Django 3.1.2 on 2022-01-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20220113_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='country',
        ),
    ]
