# Generated by Django 3.1.2 on 2022-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20220113_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='published_conference_taiwan',
            new_name='published_conference_domestic',
        ),
        migrations.AlterField(
            model_name='member',
            name='experience',
            field=models.TextField(blank=True, default='', help_text='經歷（經歷——時間）'),
        ),
    ]
