# Generated by Django 3.1.2 on 2022-01-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20220113_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='students_conference',
            field=models.TextField(blank=True, default='', help_text='主辦及參與國際會議（時間 / 會議名稱）'),
        ),
        migrations.AddField(
            model_name='member',
            name='students_honor',
            field=models.TextField(blank=True, default='', help_text='指導學生之特殊榮譽（時間 / 得獎名稱）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='awarded',
            field=models.TextField(blank=True, default='', help_text='榮譽及獲獎（時間/獲獎名稱）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='experience',
            field=models.TextField(blank=True, default='', help_text='經歷（經歷——時間）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='graduate',
            field=models.TextField(default='', help_text='學歷（國家 \\ 學校 \\ 系別 \\ 學歷(修業期間)）eg. 美國 \\ 華盛頓州立大學 \\ 資訊工程 \\ 博士(1992 ~ 1995)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='project_gen',
            field=models.TextField(blank=True, default='', help_text='一般建教案（計劃名稱 / 起迄日期 / 補助單位）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='project_tech',
            field=models.TextField(blank=True, default='', help_text='科技部計劃（計劃名稱 / 起迄日期 / 補助單位）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='students_doc',
            field=models.TextField(blank=True, default='', help_text='博士生（姓名(年級)）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='students_master',
            field=models.TextField(blank=True, default='', help_text='碩士生（姓名(年級)）'),
        ),
    ]
