# Generated by Django 3.1.2 on 2022-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_auto_20220113_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='awarded',
            field=models.TextField(blank=True, default='', help_text='榮譽及獲獎（(時間)獲獎名稱）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='experience',
            field=models.TextField(blank=True, default='', help_text='經歷（經歷(時間)）'),
        ),
    ]
