# Generated by Django 3.1.2 on 2022-01-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20220114_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='patent',
            field=models.TextField(blank=True, default='', help_text='專利號 專利名稱'),
        ),
    ]
