# Generated by Django 3.1.2 on 2022-01-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_auto_20220114_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', help_text='姓名', max_length=100),
        ),
    ]
