# Generated by Django 3.1.2 on 2022-01-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_auto_20220117_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_member',
            name='email',
            field=models.EmailField(help_text='信箱', max_length=254),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='name',
            field=models.CharField(help_text='姓名', max_length=10),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='phone',
            field=models.CharField(help_text='電話', max_length=20),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='position',
            field=models.CharField(help_text='職位', max_length=100),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='resbonsibility',
            field=models.CharField(help_text='負責業務', max_length=30),
        ),
    ]
