# Generated by Django 3.1.2 on 2022-01-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_auto_20220121_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '系所'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': '師資成員'},
        ),
        migrations.AlterModelOptions(
            name='office_member',
            options={'ordering': ['name'], 'verbose_name_plural': '系辦成員'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='輸入系所名稱', max_length=10, verbose_name='系所別'),
        ),
        migrations.AlterField(
            model_name='member',
            name='awarded',
            field=models.TextField(blank=True, default='', help_text='榮譽及獲獎（(時間)獲獎名稱）', verbose_name='榮譽及獲獎'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email1',
            field=models.EmailField(default='', help_text='E-mail', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email2',
            field=models.EmailField(blank=True, default='', help_text='E-mail', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email3',
            field=models.EmailField(blank=True, default='', help_text='E-mail', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='experience',
            field=models.TextField(blank=True, default='', help_text='經歷（經歷(時間)）', verbose_name='經歷'),
        ),
        migrations.AlterField(
            model_name='member',
            name='expertise',
            field=models.TextField(default='', help_text='專長及研究領域', verbose_name='專長及研究領域'),
        ),
        migrations.AlterField(
            model_name='member',
            name='graduate',
            field=models.TextField(default='', help_text='學歷（國家 \\ 學校 \\ 系別 \\ 學歷(修業期間)）eg. 美國 \\ 華盛頓州立大學 \\ 資訊工程 \\ 博士(1992 ~ 1995)', verbose_name='學歷'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lab',
            field=models.CharField(default='', help_text='實驗室名稱', max_length=20, verbose_name='實驗室名稱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lab_location',
            field=models.CharField(default='', help_text='實驗室位置', max_length=100, verbose_name='實驗室位置'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', help_text='輸入姓名', max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='office',
            field=models.CharField(default='資訊系館', help_text='辦公室位置', max_length=100, verbose_name='辦公室位置'),
        ),
        migrations.AlterField(
            model_name='member',
            name='patent',
            field=models.TextField(blank=True, default='', help_text='專利號 專利名稱', verbose_name='專利'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', help_text='電話，分機', max_length=20, verbose_name='電話，分機'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(default='', help_text='輸入職位', max_length=100, verbose_name='職位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='project_gen',
            field=models.TextField(blank=True, default='', help_text='一般建教案（計劃名稱 / 起迄日期 / 補助單位）', verbose_name='一般建教案'),
        ),
        migrations.AlterField(
            model_name='member',
            name='project_tech',
            field=models.TextField(blank=True, default='', help_text='科技部計劃（計劃名稱 / 起迄日期 / 補助單位）', verbose_name='科技部計劃'),
        ),
        migrations.AlterField(
            model_name='member',
            name='published_accepted_papers',
            field=models.TextField(blank=True, default='', help_text='著作——Accepted Papers to be Published', verbose_name='著作——Accepted Papers to be Published'),
        ),
        migrations.AlterField(
            model_name='member',
            name='published_conference_domestic',
            field=models.TextField(blank=True, default='', help_text='著作——Conference Papers（國內會議）', verbose_name='著作——Conference Papers（國內會議）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='published_conference_foreign',
            field=models.TextField(blank=True, default='', help_text='著作——Conference Papers（國際會議）', verbose_name='著作——Conference Papers（國際會議）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='published_refered_papers',
            field=models.TextField(blank=True, default='', help_text='著作——Refereed Papers', verbose_name='著作——Refereed Papers'),
        ),
        migrations.AlterField(
            model_name='member',
            name='students_conference',
            field=models.TextField(blank=True, default='', help_text='主辦及參與國際會議（時間 / 會議名稱）', verbose_name='主辦及參與國際會議'),
        ),
        migrations.AlterField(
            model_name='member',
            name='students_doc',
            field=models.TextField(blank=True, default='', help_text='博士生（姓名(年級)）', verbose_name='博士生'),
        ),
        migrations.AlterField(
            model_name='member',
            name='students_honor',
            field=models.TextField(blank=True, default='', help_text='指導學生之特殊榮譽（時間 / 得獎名稱）', verbose_name='指導學生之特殊榮譽'),
        ),
        migrations.AlterField(
            model_name='member',
            name='students_master',
            field=models.TextField(blank=True, default='', help_text='碩士生（姓名(年級)）', verbose_name='碩士生'),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, default='', help_text='個人網頁', max_length=100, verbose_name='個人網頁'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='email',
            field=models.EmailField(help_text='信箱', max_length=254, verbose_name='信箱'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='name',
            field=models.CharField(help_text='姓名', max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='phone',
            field=models.CharField(help_text='電話', max_length=20, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='position',
            field=models.CharField(help_text='職位', max_length=100, verbose_name='職位'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='resbonsibility',
            field=models.CharField(help_text='負責業務', max_length=30, verbose_name='負責業務'),
        ),
    ]
