# Generated by Django 3.1.2 on 2022-01-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_auto_20220125_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.ManyToManyField(to='members.Department', verbose_name='系所別'),
        ),
    ]
