# Generated by Django 3.1.2 on 2022-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_auto_20220125_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lab_website',
            field=models.CharField(blank=True, default='', help_text='實驗室網頁', max_length=200, verbose_name='實驗室網頁'),
        ),
        migrations.AlterField(
            model_name='member',
            name='graduate',
            field=models.TextField(blank=True, default='', help_text='學歷（國家 \\ 學校 \\ 系別 \\ 學歷(修業期間)）eg. 美國 \\ 華盛頓州立大學 \\ 資訊工程 \\ 博士(1992 ~ 1995)', verbose_name='學歷'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lab',
            field=models.CharField(blank=True, default='', help_text='實驗室名稱', max_length=100, verbose_name='實驗室名稱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lab_location',
            field=models.CharField(blank=True, default='', help_text='實驗室位置', max_length=100, verbose_name='實驗室位置'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', help_text='電話，分機', max_length=50, verbose_name='電話，分機'),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, default='', help_text='個人網頁', max_length=200, verbose_name='個人網頁'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='name',
            field=models.CharField(help_text='姓名', max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='phone',
            field=models.CharField(help_text='電話', max_length=50, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='resbonsibility',
            field=models.CharField(help_text='負責業務', max_length=50, verbose_name='負責業務'),
        ),
    ]
