# Generated by Django 3.1.2 on 2022-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_auto_20220422_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['my_order'], 'verbose_name_plural': '師資成員'},
        ),
        migrations.AddField(
            model_name='member',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
