# Generated by Django 3.1.2 on 2022-07-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_auto_20220708_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': '師資成員'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='my_order',
        ),
    ]
