# Generated by Django 3.1.2 on 2022-07-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_auto_20220708_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='classification',
            field=models.CharField(choices=[('Normal', '一般'), ('Adjunct', '兼任'), ('Joint', '合聘'), ('Visiting', '客座'), ('Retired', '退休')], default='Normal', max_length=20),
        ),
    ]
