# Generated by Django 3.1.2 on 2022-07-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_member_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='classification',
            field=models.CharField(choices=[('Full_time', '專任'), ('Adjunct', '兼任'), ('Joint', '合聘'), ('Visiting', '客座'), ('Retired', '退休')], default='Full_time', max_length=20, verbose_name='類別'),
        ),
    ]
