# Generated by Django 3.1.2 on 2022-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_member_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='place',
            field=models.IntegerField(choices=[('Chair', 1), ('Vice_chair', 2), ('Chair_prof', 3), ('Distinguished_prof', 4), ('Arof', 5), ('Associate_prof', 6), ('Assistant_prof', 7)], default=99, verbose_name='位置'),
        ),
    ]
