# Generated by Django 3.1.2 on 2022-07-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_auto_20220709_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['place', 'order'], 'verbose_name_plural': '師資成員'},
        ),
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.IntegerField(default=99, verbose_name='排序'),
        ),
    ]
