# Generated by Django 3.1.2 on 2022-07-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_auto_20220716_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['order', 'place'], 'verbose_name_plural': '師資成員'},
        ),
    ]
