# Generated by Django 3.1.2 on 2022-07-16 05:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_auto_20220716_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='classification',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full_time', '專任'), ('Adjunct', '兼任'), ('Joint', '合聘'), ('Visiting', '客座'), ('Retired', '退休')], default='Full_time', max_length=20, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='member',
            name='office',
            field=models.CharField(blank=True, default='資訊系館', help_text='辦公室位置', max_length=100, verbose_name='辦公室位置'),
        ),
    ]
