# Generated by Django 3.1.2 on 2022-07-16 06:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_auto_20220716_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='classification',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full_time', '專任'), ('Adjunct', '兼任'), ('Joint', '合聘'), ('Visiting', '客座'), ('Retired', '退休')], default='Full_time', max_length=40, verbose_name='類別'),
        ),
    ]
