# Generated by Django 3.1.2 on 2022-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0048_auto_20220716_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/teacher', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='office_member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/office', verbose_name='照片'),
        ),
    ]
