# Generated by Django 3.1.2 on 2022-08-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_auto_20220828_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['order', 'place'], 'verbose_name_plural': '師資'},
        ),
    ]
