# Generated by Django 3.1.2 on 2022-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0050_auto_20220828_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='輸入類別', max_length=10, verbose_name='類別')),
                ('edit_time', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '類別',
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='classification',
        ),
        migrations.AddField(
            model_name='member',
            name='classification',
            field=models.ManyToManyField(to='members.Classification', verbose_name='類別'),
        ),
    ]
