# Generated by Django 4.1 on 2022-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0051_auto_20220829_1315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/member/teacher",
                verbose_name="照片",
            ),
        ),
        migrations.AlterField(
            model_name="office_member",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/member/office",
                verbose_name="照片",
            ),
        ),
    ]
