# Generated by Django 4.1 on 2022-09-04 07:06

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0052_alter_member_photo_alter_office_member_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="office_member",
            options={"verbose_name_plural": "系辦成員"},
        ),
        migrations.RemoveField(
            model_name="office_member",
            name="name",
        ),
        migrations.RemoveField(
            model_name="office_member",
            name="position",
        ),
        migrations.RemoveField(
            model_name="office_member",
            name="resbonsibility",
        ),
        migrations.CreateModel(
            name="Office_MemberTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="姓名", max_length=20, verbose_name="姓名"),
                ),
                (
                    "position",
                    models.CharField(help_text="職位", max_length=100, verbose_name="職位"),
                ),
                (
                    "resbonsibility",
                    models.CharField(
                        help_text="負責業務", max_length=50, verbose_name="負責業務"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="members.office_member",
                    ),
                ),
            ],
            options={
                "verbose_name": "office_ member Translation",
                "db_table": "members_office_member_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
