# Generated by Django 4.1 on 2022-09-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0054_remove_member_awarded_remove_member_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="name_en",
            field=models.CharField(
                default="", help_text="輸入英文姓名", max_length=100, verbose_name="英文姓名"
            ),
        ),
    ]
