# Generated by Django 4.1 on 2022-09-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0055_member_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="membertranslation",
            name="lab",
            field=models.CharField(
                blank=True,
                default="",
                help_text="實驗室名稱",
                max_length=100,
                verbose_name="實驗室名稱",
            ),
        ),
        migrations.AddField(
            model_name="membertranslation",
            name="lab_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="實驗室位置",
                max_length=100,
                verbose_name="實驗室位置",
            ),
        ),
        migrations.AddField(
            model_name="membertranslation",
            name="office",
            field=models.CharField(
                blank=True,
                default="資訊系館",
                help_text="辦公室位置",
                max_length=200,
                verbose_name="辦公室位置",
            ),
        ),
        migrations.AddField(
            model_name="membertranslation",
            name="position",
            field=models.CharField(
                default="", help_text="輸入職位", max_length=100, verbose_name="職位"
            ),
        ),
    ]
